//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolment
    {
        public int EnrolmentID { get; set; }
        public Nullable<decimal> Grade { get; set; }
        public Nullable<bool> EnrolmentComplete { get; set; }
        public int StudentID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
